// <auto-generated />
using System;
using BookMyCut.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyCut.dataa.Migrations
{
    [DbContext(typeof(BookMyCutContext))]
    partial class BookMyCutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("BookMyCut.Data.Models.Disponibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoiffeurId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstReserve")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoiffeurId");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("BookMyCut.Data.Models.RendezVous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoiffeurId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoiffeurId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("BookMyCut.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BookMyCut.Data.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            MotDePasse = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            NomComplet = "Administrateur",
                            Role = 2
                        });
                });

            modelBuilder.Entity("BookMyCut.Data.Models.Disponibilite", b =>
                {
                    b.HasOne("BookMyCut.Data.Models.Utilisateur", "Coiffeur")
                        .WithMany()
                        .HasForeignKey("CoiffeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coiffeur");
                });

            modelBuilder.Entity("BookMyCut.Data.Models.RendezVous", b =>
                {
                    b.HasOne("BookMyCut.Data.Models.Utilisateur", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMyCut.Data.Models.Utilisateur", "Coiffeur")
                        .WithMany()
                        .HasForeignKey("CoiffeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMyCut.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coiffeur");

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
